-- Jump with ctrl+hjkl
-- Note: These are now handled by vim-tmux-navigator for seamless vim/tmux navigation
-- vim.keymap.set('n', '<C-h>', '<C-w>h');
-- vim.keymap.set('n', '<C-j>', '<C-w>j');
-- vim.keymap.set('n', '<C-k>', '<C-w>k');
-- vim.keymap.set('n', '<C-l>', '<C-w>l');
